stages:
  - docker

build:docker-tag:
  only:
    - tags
  variables:
    DOCKER_DRIVER: overlay2
    GIT_SUBMODULE_STRATEGY: recursive
  image: docker:stable-git
  stage: docker
  tags:
    - linux-dind
  before_script:
    - git submodule sync --recursive
    - git submodule update --recursive --remote
    - docker login $DOCKER_REGISTRY -u $DOCKER_REGISTRY_USER -p $DOCKER_REGISTRY_PASS
  script:
    - docker build -t "$DOCKER_REGISTRY/$CI_PROJECT_NAME:$CI_COMMIT_TAG" .
  after_script:
    - docker push "$DOCKER_REGISTRY/$CI_PROJECT_NAME:$CI_COMMIT_TAG"

build:docker-master:
  only:
    - master
  variables:
    DOCKER_DRIVER: overlay2
    GIT_SUBMODULE_STRATEGY: recursive
  image: docker:stable-git
  stage: docker
  tags:
    - linux-dind
  before_script:
    - git submodule sync --recursive
    - git submodule update --recursive --remote
    - docker login $DOCKER_REGISTRY -u $DOCKER_REGISTRY_USER -p $DOCKER_REGISTRY_PASS
  script:
    - docker build -t "$DOCKER_REGISTRY/$CI_PROJECT_NAME:latest" -t "$DOCKER_REGISTRY/$CI_PROJECT_NAME:$CI_COMMIT_SHA" .
  after_script:
    - docker push "$DOCKER_REGISTRY/$CI_PROJECT_NAME:latest"
    - docker push "$DOCKER_REGISTRY/$CI_PROJECT_NAME:$CI_COMMIT_SHA"
